### ISSUE TITLE
SMLoadr itself crashes.

### ISSUE THREAD

**Issue by stephanie00100** [thelucifermorningstar/SMLoadr-AUX#12]
I attempt to download something in SMLoadr-AUX, it launches SMLoadr and less than a second? SMLoadr crashes/shuts down. If I run SMLoadr by itself, it starts just fine.

**Comment by thelucifermorningstar** [comment]
Bug fix in the next update. Thanks :)

**Comment by irockdude554** [comment]
when can we expect the next update?

**Comment by bascurtiz** [comment]
@stephanie00100 
Fixed since v1.0.4.

@irockdude554 
Right now! Check out v1.0.5.

**Comment by callumj2** [comment]
@thelucifermorningstar  I'm running into this exact same issue in v2, any clue what could be causing this?

**Comment by thelucifermorningstar** [comment]
@callumj2 which OS?
I've tested it on Win 7 & 10.
Make sure SMLoadr AUX.exe is in the same folder as SMloadr-Win-x64.exe.

The cmd/cli should show some error-message.
Since it closes directly I assume, it's hard to print-screen it.
You could screen-record it with OBS or gyazo.com etc. to capture that moment.

**Comment by callumj2** [comment]
Hey man thank you for getting back to me!
The issue has randomly stopped happening although it is downloading a lot slower now! If it happens again I'll screen record and try to catch the error message :)
