### ISSUE TITLE
Can't set download folder; crash

### ISSUE THREAD

**Issue by manbitesdog23** [thelucifermorningstar/SMLoadr-AUX#40]
Hi

SMLoadr AUX 1.0.6 for SMloader v1.10.0 crashes when trying to set the download folder on first use. If you leave the options at default, it will download and create a DOWNLOADS folder within the same directory as SMloadr AUX. However, you cannot modify this. Please take a look at the crash report.

Thanks

<img width="332" alt="crash" src="https://user-images.githubusercontent.com/54751309/71411714-6e648580-2642-11ea-8f5b-bf01efd4f555.PNG">

**Comment by thelucifermorningstar** [comment]
@manbitesdog23 
Correct.
SMLoadr v1.10.0 ditched the -p (ath) feature, so no way to set it manually.
Hence stated: 
*"For best compatibility, extract in same location next to where SMLoadr is located (not a subfolder)."*

SMLoadr creates a DOWNLOADS folder, whenever u download something.
Hence when you put AUX in the same folder as SMLoadr, all is good.

You obviously didn't download something already, or you didn't put it in the same folder as SMLoadr.
Hence the error. (Not a crash, since u can just hit Continue and you're good to go)

---

If you do however want to set the folder manually, you need to use previous SMLoadr, v1.9.5.
I've made a variant for it, [here](https://github.com/thelucifermorningstar/SMLoadr-AUX/releases/tag/1.0.7).

**Comment by thelucifermorningstar** [comment]
Version 1.20.0 of SMloadr added back the -p (ath).
Updated AUX to 1.10.1 to make it compatible & much more.
