### ISSUE TITLE
Not downloading FLAC

### ISSUE THREAD

**Issue by showmak** [thelucifermorningstar/SMLoadr-AUX#52]
Used "MP3 - 128 kbps" because "FLAC - 1411 kbps" wasn't available

Is this normal?

**Comment by showmak** [comment]
Do I have to have a HiFi Account? Because I am on a Free Account.

**Comment by thelucifermorningstar** [comment]
@showmak 
song or album url?
do note, some songs are not available on deezer in high quality (but most are).
u don't need anything other than a free account.

**Comment by MReprogle1** [comment]
I am also having this same issue. I went back and tried re-downloading albums that I previously downloaded FLAC files of, and even those are telling me:

Used "MP3 - 128 kbps" because "FLAC - 1411 kbps" wasn't available

It seems like it is more of an issue with SMLoadr than it is with AUX.

**Comment by MReprogle1** [comment]
Found this fix. If you don't have your SMLoadr updated to 1.23.0, it will only download 128kbps. As soon as I updated to 1.23.0, all went back to normal. This was due to a change of the API on Deezer's side.

The SMLoadr git page doesn't currently have the .exe file you need for Windows, but you can get all executables off of their Telegram feed (create a Telegram account, then it will let you download through the app). I think this is due to the fix being a temporary workaround, but I would imagine their main git page puts the executables up at some point.

**Comment by MReprogle1** [comment]
> Used "MP3 - 128 kbps" because "FLAC - 1411 kbps" wasn't available
> 
> Is this normal?

Found this fix. If you don't have your SMLoadr updated to 1.23.0, it will only download 128kbps. As soon as I updated to 1.23.0, all went back to normal. This was due to a change of the API on Deezer's side.

The SMLoadr git page doesn't currently have the .exe file you need for Windows, but you can get all executables off of their Telegram feed (create a Telegram account, then it will let you download through the app). I think this is due to the fix being a temporary workaround, but I would imagine their main git page puts the executables up at some point.

**Comment by showmak** [comment]
> > Used "MP3 - 128 kbps" because "FLAC - 1411 kbps" wasn't available
> > Is this normal?
> 
> Found this fix. If you don't have your SMLoadr updated to 1.23.0, it will only download 128kbps. As soon as I updated to 1.23.0, all went back to normal. This was due to a change of the API on Deezer's side.
> 
> The SMLoadr git page doesn't currently have the .exe file you need for Windows, but you can get all executables off of their Telegram feed (create a Telegram account, then it will let you download through the app). I think this is due to the fix being a temporary workaround, but I would imagine their main git page puts the executables up at some point.

Thanks, but where can I download SMLoadr 1.23.0 .exe file? The one which I have is version 1.10.2

**Comment by showmak** [comment]
It appears I am using the wrong version of SMLoadr, where can I get SMLoadr 1.23.0 .exe file?
![2020-05-31_14-02-29](https://user-images.githubusercontent.com/17910813/83351588-f2d3d680-a34d-11ea-81f9-df57adeeb1d0.jpg)

**Comment by thelucifermorningstar** [comment]
@showmak 
Here: https://t.me/SMLoadrNews
