### ISSUE TITLE
Edit SMLoadr "naming" settings from SMLoadr-AUX

### ISSUE THREAD

**Issue by mauriva** [thelucifermorningstar/SMLoadr-AUX#53]
I think that for change "naming" settings for SMLoadr you can edit the file SMLoadrConfig.json.
Although I edited that file, it appears that my changes have no effect.
I wanted to know if it is possible to add these settings in SMLoader-AUX both to make changes to the path easier and to make these changes effective.

**Comment by thelucifermorningstar** [comment]
@mauriva 
Since SMLoadr v1.20.0 according to the changelog:

_- Updated packages_
_- Removed update checker_
_- Removed debug logger_
**_- Removed customization for folders & filenames from config and brought back -p(ath) argument_** 

_Be advised that using -p with full paths will always produce invalid file paths in m3u playlists, needing manual correction. Little did you know, It's always been this way and never meant to be used with full paths._
